-keepnames class io.github.ovso.worship.view.ui.home.HomeFragment
-keepnames class io.github.ovso.worship.view.ui.bookmark.BookmarkFragment
-keepnames class io.github.ovso.worship.view.ui.history.HistoryFragment