# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "worship app"
  lane :distribute do
      firebase_app_distribution(
          app: "1:179750580509:android:8b348bd687c7e31fc671f4",
          firebase_cli_token: "1//0eVnJuJC6EnlDCgYIARAAGA4SNwF-L9IroWgSUbEx5BueQrBNrcDfesBI7DiuZONm7nW2vGZTlFmG6Bs_etKFzAq5NIgTyjlLgOM",
          testers: "ovsoc@daum.net, ovso@naver.com",
          release_notes: "Lots of amazing new features to test out!",
          apk_path: "/Users/jaeho/Documents/workspace_side/RealTimeWorship/app/build/outputs/apk/debug/worship-1.1.1-debug.apk"
      )

  end
end
